Repository bts-lasalle-avignon-projets/MP25-T2-PICKOMINO, pull requests merged in 2025-02, with the labels that each got.

#64 Ajout d'une fonctionnalité pour relancer une partie
  src/Ihm.cpp
  src/Ihm.h
  src/Jeu.cpp
Labels: feature

#65 54 création d une ia
  src/Ia.cpp
  src/Ia.h
  src/Ihm.cpp
  src/Ihm.h
  src/Jeu.cpp
  src/Jeu.h
  src/Joueur.cpp
  src/Joueur.h
Labels: feature

#67 Modifications IA + Nouveau mode de jeu
  src/Ihm.cpp
  src/Ihm.h
  src/Jeu.cpp
  src/Jeu.h
Labels: feature

#71 Release V1.2
  README.md
  images/pickomino.gif
  src/Ia.cpp
  src/Ia.h
  src/Ihm.cpp
  src/Ihm.h
  src/Jeu.cpp
  src/Jeu.h
  src/Joueur.cpp
  src/Joueur.h
Labels: release

#72 Main
  README.md
  images/pickomino.gif
  src/Ia.cpp
  src/Ia.h
  src/Ihm.cpp
  src/Ihm.h
  src/Jeu.cpp
  src/Jeu.h
Labels: task

#74 Ajout du consentement pour la récupération de l'âge des joueurs et ajustement de l'ordre de jeu
  Makefile
  src/Ia.cpp
  src/Ia.h
  src/Ihm.cpp
  src/Ihm.h
  src/Jeu.cpp
  src/Jeu.h
  src/Joueur.cpp
  src/Joueur.h
  src/Plateau.h
  tests/planDeTest.md
  tests/testsCalculerScoreFinal.cpp
  tests/testsTrouverPlusJeune.cpp
Labels: feature

#75 Correction du bug + Modif message creation joueur
  src/Ihm.cpp
  src/Jeu.cpp
Labels: bug
